<?php

use Magento\Framework\App\Action\Action;

?>

<?php
$marketPlaceHelper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$urlHelper = $this->helper(\Magento\Framework\Url\Helper\Data::class);
$fabeuHelper = $this->helper(\Fabeu\Shop\Helper\Data::class);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$sellerId = '';
$vendorlogo = $fabeuHelper->getVendorLogoByProductId($currentProduct->getId());
$shopUrl = $fabeuHelper->getSellerShopUrlByProductId($currentProduct->getId());
$count = !empty($block->getData('prduct_count')) ? $block->getData('prduct_count') : 8;
$sellerId=$fabeuHelper->getSellerIdByProductId($currentProduct->getId());
$_productCollection=[];
if ($sellerId != "") {
    $_productCollection = $marketPlaceHelper->getSellerProductCollection($sellerId, 0, $count);
}
//$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
$uniqId = uniqid('block_');
//echo '<pre>';print_r(!empty($_productCollection) );echo '</pre>';die('call')
?>

<?php /*if (empty($_productCollection)): */?><!--
    <div class="message info empty">
        <div><?php /*/* @escapeNotVerified */
            //echo __('We can\'t find products matching the selection.') */?></div>
    </div>-->
<?php if (!empty($_productCollection)): ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'slider';
    $image = 'category_page_grid';
    $image_hover = 'category_page_grid_hover';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $classid = $block->getBlockId();//uniqid();//md5(json_encode($block->getData()));

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $sliderItem = $block->getData('slider_item') ? $block->getData('slider_item') : 4;
    $swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Codazon_ProductFilter::swatches/renderer.phtml');
    ?>
    <div class="block-title title">
        <strong id="block-other-heading" role="heading" aria-level="2"><?= ($title)?$title:'' ?></strong>
    </div>
    <div class="block widget block-products-list fab-other-products <?php /* @escapeNotVerified */
    echo $viewMode; ?>" id="<?php echo $uniqId ?>">
        <?php /*if ($title): */?><!--
            <div class="cdz-block-title">
                <h2 class="b-title"><span><?php /*/* @escapeNotVerified */
                        //echo $title; */?></span></h2>
            </div>
        --><?php /*endif */?>
        <div class="block-content">
            <div class="products products-grid wrapper <?php /* @escapeNotVerified */
            echo $viewMode; ?> products-<?php /* @escapeNotVerified */
            echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <div class="products list items product-items <?php echo $block->getData('show_slider') ? 'cdz-slider' : '' ?>"
                    <?php if ($block->getData('show_slider')) : ?>
                        <?php $slider_item = ($block->getData('slider_item')) ? $block->getData('slider_item') : 6 ?>
                        data-items="<?php echo $slider_item ?>"
                        data-items-0="2"
                        data-items-480="2"
                        data-items-768="<?php echo abs($slider_item - 2) ?>"
                        data-items-1024="<?php echo abs($slider_item - 1) ?>"
                        data-items-1280="<?php echo $slider_item ?>"
                        data-items-1440="<?php echo $slider_item ?>"
                        data-loop="false"
                        data-margin="20"
                        data-autoWidth="false"
                    <?php endif; ?>
                >
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php /* @escapeNotVerified */
                        echo ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <div class="cdz-hover-section">
                                <div class="cdz-product-top">
                                    <?php
                                    $imagewidth = !empty($block->getData('width')) ? $block->getData('width') : 280;
                                    $imageheight = !empty($block->getData('height')) ? $block->getData('width') : 392;
                                    $imageHelper = $objectManager->get('\Magento\Catalog\Helper\Image');
                                    $image_url = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imagewidth, $imageheight)->getUrl();
                                    $hover_image_url = $imageHelper->init($_product, 'product_small_image')->setImageFile($_product->getFile())->resize($imagewidth, $imageheight)->getUrl();
                                    $productImage = $block->getImage($_product, $image);
                                    $productHoverImage = $block->getImage($_product, $image_hover);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php // Product Image ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
						                <span class="main-image">
                                            <span class="product-image-container"
                                                  style="width:<?php echo $imagewidth . 'px' ?>;">
                                                                                            <span class="product-image-wrapper"
                                                                                                  style="padding-bottom: 140%;">
                                                                                                <img class=""
                                                                                                     src="<?php echo $image_url; ?>"
                                                                                                     max-width="<?php echo $imagewidth ?>"
                                                                                                     max-height="<?php echo $imageheight ?>"
                                                                                                     alt="<?php /* @escapeNotVerified */
                                                                                                     echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"></span>
                                                                                        </span>
										</span>
                                        <span class="hover-image">
                                            <span class="product-image-container"
                                                  style="width:<?php echo $imagewidth . 'px' ?>;">
                                                <span class="product-image-wrapper" style="padding-bottom: 140%;">
                                                    <img class="" src="<?php echo $hover_image_url; ?>"
                                                         max-width="<?php echo $imagewidth ?>"
                                                         max-height="<?php echo $imageheight ?>"
                                                         alt="<?php /* @escapeNotVerified */
                                                         echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"></span>
                                            </span>
										</span>
                                    </a>

                                    <div class="cdz-product-wishlist">

                                        <div class="actions-secondary show-tooltip" data-role="add-to-links"
                                             title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>

                                    </div>


                                    <?php $labelHelper->showLabel($_product) ?>
                                </div>
                            </div>
                            <div class="product details product-item-details">
                                <div class="info-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>

                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>

                                    <!-- <?php /*if($block->isShow('review')): */ ?>
                                    <?php /*echo $block->getReviewsSummaryHtml($_product, $templateType); */ ?>
                                    --><?php /*endif */ ?>

                                    <?php /* @escapeNotVerified */
                                    echo $block->getProductPrice($_product) ?>

                                    <?php echo $swatchesRender->setProduct($_product)->toHtml() ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                    <?php /*if($block->isShow('description')): */ ?><!--
                                        <div class="product description product-item-description">
                                            <?php /*/* @escapeNotVerified */ //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') */?>
                                            <a href="<?php /*/* @escapeNotVerified */ //echo $_product->getProductUrl() */?>" title="<?php /*/* @escapeNotVerified */ //echo $_productNameStripped */?>"
                                               class="action more"><?php /*/* @escapeNotVerified */ //echo __('Learn More') */?></a>
                                        </div>
                                    --><?php /*endif; */ ?>
                                </div>
                                <div class="product-item-inner">
                                    <div class="product-btn-actions">
                                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                            <?php /*if($block->isShow('addtocart')): */ ?>
                                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php
                                                    //$postParams = $block->getAddToCartPostParams($_product);
                                                    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
                                                    $url = $listBlock->getAddToCartUrl($_product);
                                                    //$url = $this->getAddToCartUrl($product,$additional);
                                                    $postParams = [
                                                        'action' => $url,
                                                        'data' => [
                                                            'product' => $_product->getEntityId(),
                                                            \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED =>
                                                                $urlHelper->getEncodedUrl($url),
                                                        ]
                                                    ];


                                                    ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                    echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?php /* @escapeNotVerified */
                                                               echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */
                                                        echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                               value="<?php /* @escapeNotVerified */
                                                               echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <!-- --><?php /*endif */ ?>
                                        </div>
                                        <div class="addto-hover-container">
                                            <div class="addto-button">
                                                <?php echo $this->helper('Codazon\QuickShop\Helper\Data')->getQuickShopButton($_product) ?>
                                            </div>
                                        </div>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                                                                                   <span><?php /* @escapeNotVerified */
                                                                                                       echo __('Add to Compare') ?></span>
                                        </a>

                                    </div>
                                    <div class="product-shop-img">
                                        <a href="<?= $escaper->escapeUrl($shopUrl); ?>"> <img src="<?= $vendorlogo; ?>" alt="logo"></a>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <?php echo ($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php echo $block->getToolbarHtml() ?>

            <script type="text/x-magento-init">
            				{
            				    "[data-role=tocart-form], .form.map.checkout": {
            				        "catalogAddToCart": {}
            				    }
            				}




            </script>
            <?php /*if (!$block->isRedirectToCartEnabled()) : */ ?><!--
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			--><?php /*endif; */ ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery', 'Magento_Theme/js/fastest_fashion'], function ($) {
        var $_productWrap = $("#<?php echo $uniqId ?>");
        console.log($_productWrap)
        //$_productWrap.sameHeightItems();
        //$_productWrap.appearingEffect();
    });
</script>